var dir_7aed1e4eb701a7767d099dababba95e4 =
[
    [ "Gasoline.Test.AssemblyInfo.cs", "_gasoline_8_test_8_assembly_info_8cs.html", null ],
    [ "Gasoline.Test.Program.cs", "_gasoline_8_test_8_program_8cs.html", [
      [ "AutoGeneratedProgram", "class_auto_generated_program.html", null ]
    ] ]
];