var hierarchy =
[
    [ "Gasoline.Api.Models.Home.AddGasStationViewModel", "class_gasoline_1_1_api_1_1_models_1_1_home_1_1_add_gas_station_view_model.html", null ],
    [ "AutoGeneratedProgram", "class_auto_generated_program.html", null ],
    [ "Controller", null, [
      [ "Gasoline.Api.Controllers.HomeController", "class_gasoline_1_1_api_1_1_controllers_1_1_home_controller.html", null ]
    ] ],
    [ "ControllerBase", null, [
      [ "Gasoline.Api.Controllers.FuelTypesController", "class_gasoline_1_1_api_1_1_controllers_1_1_fuel_types_controller.html", null ],
      [ "Gasoline.Api.Controllers.GasStationController", "class_gasoline_1_1_api_1_1_controllers_1_1_gas_station_controller.html", null ]
    ] ],
    [ "DbContext", null, [
      [ "Gasoline.Data.EF.GasolineContext", "class_gasoline_1_1_data_1_1_e_f_1_1_gasoline_context.html", null ]
    ] ],
    [ "Gasoline.Data.Models.FuelType", "class_gasoline_1_1_data_1_1_models_1_1_fuel_type.html", null ],
    [ "Gasoline.Data.Models.GasStation", "class_gasoline_1_1_data_1_1_models_1_1_gas_station.html", null ],
    [ "Gasoline.Api.Models.Home.GasStationDetailsViewModel", "class_gasoline_1_1_api_1_1_models_1_1_home_1_1_gas_station_details_view_model.html", null ],
    [ "Gasoline.Data.Models.GasStationFuel", "class_gasoline_1_1_data_1_1_models_1_1_gas_station_fuel.html", null ],
    [ "Gasoline.Api.Models.Home.GasStationFuelViewModel", "class_gasoline_1_1_api_1_1_models_1_1_home_1_1_gas_station_fuel_view_model.html", null ],
    [ "Gasoline.Data.Services.IFuelTypeService", "interface_gasoline_1_1_data_1_1_services_1_1_i_fuel_type_service.html", [
      [ "Gasoline.Data.Services.FuelTypeService", "class_gasoline_1_1_data_1_1_services_1_1_fuel_type_service.html", null ]
    ] ],
    [ "Gasoline.Data.Services.IGasStationService", "interface_gasoline_1_1_data_1_1_services_1_1_i_gas_station_service.html", [
      [ "Gasoline.Data.Services.GasStationService", "class_gasoline_1_1_data_1_1_services_1_1_gas_station_service.html", null ]
    ] ],
    [ "ITestCaseOrderer", null, [
      [ "Gasoline.Test.UnitTest", "class_gasoline_1_1_test_1_1_unit_test.html", null ]
    ] ],
    [ "Migration", null, [
      [ "Gasoline.Data.Migrations.init", "class_gasoline_1_1_data_1_1_migrations_1_1init.html", null ],
      [ "Gasoline.Data.Migrations.init1", "class_gasoline_1_1_data_1_1_migrations_1_1init1.html", null ],
      [ "Gasoline.Data.Migrations.init2", "class_gasoline_1_1_data_1_1_migrations_1_1init2.html", null ]
    ] ],
    [ "ModelSnapshot", null, [
      [ "Gasoline.Data.Migrations.GasolineContextModelSnapshot", "class_gasoline_1_1_data_1_1_migrations_1_1_gasoline_context_model_snapshot.html", null ]
    ] ],
    [ "Gasoline.Api.Program", "class_gasoline_1_1_api_1_1_program.html", null ],
    [ "RazorPage", null, [
      [ "AspNetCore.Views__ViewImports", "class_asp_net_core_1_1_views_____view_imports.html", null ],
      [ "AspNetCore.Views__ViewStart", "class_asp_net_core_1_1_views_____view_start.html", null ],
      [ "AspNetCore.Views_Home_AddGasStationView", "class_asp_net_core_1_1_views___home___add_gas_station_view.html", null ],
      [ "AspNetCore.Views_Home_GasStationView", "class_asp_net_core_1_1_views___home___gas_station_view.html", null ],
      [ "AspNetCore.Views_Home_Index", "class_asp_net_core_1_1_views___home___index.html", null ],
      [ "AspNetCore.Views_Shared__CookieConsentPartial", "class_asp_net_core_1_1_views___shared_____cookie_consent_partial.html", null ],
      [ "AspNetCore.Views_Shared__Layout", "class_asp_net_core_1_1_views___shared_____layout.html", null ],
      [ "AspNetCore.Views_Shared__ValidationScriptsPartial", "class_asp_net_core_1_1_views___shared_____validation_scripts_partial.html", null ]
    ] ],
    [ "RazorPage< List< Gasoline.Api.Models.Home.GasStationFuelViewModel >>", null, [
      [ "AspNetCore.Views_Home_CheapestFuelByIdView", "class_asp_net_core_1_1_views___home___cheapest_fuel_by_id_view.html", null ]
    ] ],
    [ "RazorPage< List< Gasoline.Data.Models.FuelType >>", null, [
      [ "AspNetCore.Views_Home_AllFuelsView", "class_asp_net_core_1_1_views___home___all_fuels_view.html", null ]
    ] ],
    [ "RazorPage< List< GasStation >>", null, [
      [ "AspNetCore.Views_Home_AllStationsView", "class_asp_net_core_1_1_views___home___all_stations_view.html", null ]
    ] ],
    [ "Gasoline.Data.Services.ServiceBase", "class_gasoline_1_1_data_1_1_services_1_1_service_base.html", [
      [ "Gasoline.Data.Services.FuelTypeService", "class_gasoline_1_1_data_1_1_services_1_1_fuel_type_service.html", null ],
      [ "Gasoline.Data.Services.GasStationService", "class_gasoline_1_1_data_1_1_services_1_1_gas_station_service.html", null ]
    ] ],
    [ "Gasoline.Api.Startup", "class_gasoline_1_1_api_1_1_startup.html", null ]
];