// <auto-generated />
using System;
using Gasoline.Data.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Gasoline.Data.Migrations
{
    [DbContext(typeof(GasolineContext))]
    partial class GasolineContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Gasoline.Data.Models.FuelType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FuelName");

                    b.HasKey("Id");

                    b.ToTable("FuelType");

                    b.HasData(
                        new { Id = new Guid("1b4da7c2-df0c-4e61-9e57-b39123b335db"), FuelName = "Benzyna 95" },
                        new { Id = new Guid("2b29eff4-77c5-42d3-9ad4-dd32d4ccb41e"), FuelName = "Benzyna 98" },
                        new { Id = new Guid("0fbaa67e-ce11-4e71-bb00-5a9c10701b34"), FuelName = "Diesel" },
                        new { Id = new Guid("fb46fb8f-010c-4d05-b102-baae43dac348"), FuelName = "LPG" }
                    );
                });

            modelBuilder.Entity("Gasoline.Data.Models.GasStation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<string>("Name");

                    b.Property<string>("PostalCode");

                    b.Property<string>("Street");

                    b.HasKey("Id");

                    b.ToTable("GasStation");

                    b.HasData(
                        new { Id = new Guid("60a4ef9c-7664-440e-804c-a5acf530a529"), City = "Czciana", Name = "Lotos", PostalCode = "69-666", Street = "Czciana" },
                        new { Id = new Guid("e64e5e92-9701-4f5f-95db-d55f20d20210"), City = "Wysoka Gogolowska", Name = "BP", PostalCode = "36-061", Street = "Strumykowa" }
                    );
                });

            modelBuilder.Entity("Gasoline.Data.Models.GasStationFuel", b =>
                {
                    b.Property<Guid>("GasStationId");

                    b.Property<Guid>("FuelTypeId");

                    b.Property<DateTime>("LastUpdateUtc");

                    b.Property<decimal>("Price");

                    b.HasKey("GasStationId", "FuelTypeId");

                    b.HasIndex("FuelTypeId");

                    b.ToTable("GasStationFuel");
                });

            modelBuilder.Entity("Gasoline.Data.Models.GasStationFuel", b =>
                {
                    b.HasOne("Gasoline.Data.Models.FuelType", "FuelType")
                        .WithMany()
                        .HasForeignKey("FuelTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Gasoline.Data.Models.GasStation")
                        .WithMany("GasStationFuels")
                        .HasForeignKey("GasStationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
